eureka:
  instance:
    #hostname: ec2-18-184-143-16.eu-central-1.compute.amazonaws.com
    #hostname: ec2-18-197-6-211.eu-central-1.compute.amazonaws.com
    hostname: localhost
  client:
    service-url:
      #defaultZone: http://eureka_admin:eureka123@ec2-18-197-6-211.eu-central-1.compute.amazonaws.com:8761/eureka/
      defaultZone: http://eureka_admin:eureka123@localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
            
spring:
  sleuth:
    enabled: true
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*|.+favicon.*)
  zipkin:
    enabled: true
    baseUrl: http://localhost:8400
    #baseUrl: http://35.156.26.200:8400
  security:
    basic:
      enabled: true
    user:
      name: eureka_admin
      password: eureka123
      