eureka:
  instance:
    hostname: 35.157.233.43
  client:
    service-url:
      defaultZone: http://35.157.233.43:8761/eureka/

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
            
spring:
  sleuth:
    enabled: true
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*|.+favicon.*)
  zipkin:
    enabled: true
    baseUrl: http://localhost:8400