eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
            
spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://localhost:8400
  cloud:
    config:
      override-system-properties: false