eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
            
spring:
  cloud:
    config:
      uri: http://localhost:8888
      username: frankker
      password: test123
  sleuth:
    enabled: true
    sampler:
      percentage: 1.0
    web:
      skipPattern: (^cleanup.*|.+favicon.*)
  zipkin:
    enabled: true
    baseUrl: http://localhost:8400